# Alexa Prompts Language Constants

WELCOME_MESSAGE = "WELCOME_MESSAGE"
WHAT_CAN_SKILL_DO = "WHAT_CAN_SKILL_DO"
SKILL_NAME = "SKILL_NAME"
GET_FACT_MESSAGE = "GET_FACT_MESSAGE"
HELP_MESSAGE = "HELP_MESSAGE"
HELP_REPROMPT = "HELP_REPROMPT"
FALLBACK_MESSAGE = "FALLBACK_MESSAGE"
FALLBACK_REPROMPT = "FALLBACK_REPROMPT"
ERROR_MESSAGE = "ERROR_MESSAGE"
STOP_MESSAGE = "STOP_MESSAGE"
FACTS = "FACTS"
WHATS_NEXT = "WHATS_NEXT"